language: csharp
sudo: required

dist: trusty
dotnet: 2.1.301
mono: latest
solution: Mono.Cecil.sln

before_install:
  - mono --version
  - ls -lh /usr/lib/mono
install:
  - dotnet restore Mono.Cecil.sln -v m
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - FrameworkPathOverrideForMono=/usr/lib/mono dotnet build Mono.Cecil.sln
  
  - dotnet test Mono.Cecil.sln --no-build -f netcoreapp2.1
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe Mono.Cecil.net35.nunit
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe Mono.Cecil.net40.nunit
  