version: 0.9.6.{build}
image: Visual Studio 2017
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore Mono.Cecil.sln --verbosity m
build_script:
  - cmd: dotnet build --no-restore Mono.Cecil.sln --verbosity m

test_script:
  - cmd: dotnet test Mono.Cecil.sln --no-build -f netcoreapp2.1
  - nunit-console.exe Mono.Cecil.net35.nunit
  - nunit-console.exe Mono.Cecil.net40.nunit
  
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/925de8a68a6d8d3ce68e
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true